name: windows

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
    tags:
      - 'v*'
    branches:
      - main
      - 'test-*'
    paths-ignore:
      - '**/README.md'

jobs:
  mix_test:
    runs-on: windows-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              msbuild_platform: ARM64
              vcvarsall: amd64_arm64
              CMAKE_GENERATOR_TYPE: "Visual Studio 17"
              CMAKE_TOOLCHAIN_FILE: "cc_toolchain/aarch64-windows-msvc.cmake"
          - pair:
              msbuild_platform: x64
              vcvarsall: x64

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.1
          elixir-version: 1.14.1
          rebar3-version: 3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.pair.vcvarsall }}
      
      - uses: cocoa-xu/cuda-toolkit@v0.2.9
        id: cuda-toolkit
        with:
          cuda: '11.8.0'

      - name: Check NVCC
        shell: bash
        run: |
          nvcc || true
