name: windows

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
    tags:
      - 'v*'
    branches:
      - main
      - 'test-*'
    paths-ignore:
      - '**/README.md'

jobs:
  mix_test:
    runs-on: windows-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              msbuild_platform: x64
              vcvarsall: x64

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.1
          elixir-version: 1.14.1
          rebar3-version: 3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.pair.vcvarsall }}
      
      - uses: cocoa-xu/cuda-toolkit@v0.3.0
        id: cuda-toolkit
        with:
          cuda: '11.8.0'
          cudnn: '8.7.0'

      - name: Check NVCC
        shell: bash
        run: |
          ls -la $CUDA_PATH
          ls -la "$CUDA_PATH\\bin" || true
          ls -la "$CUDA_PATH/bin" || true
          
          ls -la "$CUDA_PATH\\lib\\x64" || true
          ls -la "$CUDA_PATH/lib/x64" || true
          
          ls -la "$CUDA_PATH\\include" || true
          ls -la "$CUDA_PATH/include" || true
