name: windows-x86_64

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
    tags:
      - 'v*'
    branches:
      - main
      - 'test-*'
    paths-ignore:
      - '**/README.md'

jobs:
  mix_test:
    runs-on: windows-latest
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0.2
          elixir-version: 1.13.4
          rebar3-version: 3.14.3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Mix Compile
        run: |
          mix deps.get
          mix compile
      
      - name: Mix Test
        run: |
          mix test
        
      - name: Test the example project
        run: |
          cd exmaple
          mix deps.get
          mix test
          cd ..

      - name: Rebar3 Compile
        shell: bash
        run: |
          export PATH="/c/Users/runneradmin/.mix:${PATH}"
          rebar3 compile

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          cd _build/test/lib/dll_loader_helper/priv
          tar -cvzf ../../../../../dll_loader_helper-${GITHUB_REF##*/}.tar.gz .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dll_loader_helper-*.tar.gz
