name: windows-x86_64

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
    tags:
      - 'v*'
    branches:
      - main
      - 'test-*'
    paths-ignore:
      - '**/README.md'

jobs:
  mix_test:
    runs-on: windows-latest
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0.2
          elixir-version: 1.13.4

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Mix Compile
        run: |
          mix deps.get
          mix compile
      
      - name: rebar Compile
        run: |
          c:/Users/runneradmin/.mix/rebar3 compile
