name: windows-x86_64

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
    tags:
      - 'v*'
    branches:
      - main
      - 'test-*'
    paths-ignore:
      - '**/README.md'

jobs:
  mix_test:
    runs-on: windows-latest
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0.2
          elixir-version: 1.13.4
          rebar3-version: 3.14.3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Mix Compile
        run: |
          mix deps.get
          mix compile
      
      - name: Mix Test
        run: |
          mix test
        
      - name: Test the Elixir example
        shell: bash
        run: |
          cd example/elixir
          rm -rf _build build build_dll
          mix deps.get
          mix test
          rm -rf _build build build_dll
          cd ../..

      - name: Rebar3 Compile
        shell: bash
        run: |
          export PATH="/c/Users/runneradmin/.mix:${PATH}"
          rm -rf _build build build_dll
          rebar3 compile
          rm -rf _build build build_dll

      - name: Test the Erlang example
        shell: bash
        run: |
          export PATH="/c/Users/runneradmin/.mix:${PATH}"
          cd example/erlang
          rm -rf _build build build_dll
          rebar3 compile
          rebar3 eunit
