name: windows

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
    tags:
      - 'v*'
    branches:
      - main
      - 'test-*'
    paths-ignore:
      - '**/README.md'

jobs:
  mix_test:
    runs-on: windows-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              msbuild_platform: x64
              vcvarsall: x64

    steps:
      - uses: actions/checkout@v3
      
      - uses: cocoa-xu/cuda-toolkit@v0.3.0
        id: cuda-toolkit
        with:
          cuda: '11.8.0'
          cudnn: '0.2.0'
          cudnn_url: ${{ secrets.CUDNN_870_WIN_URL }}

      - name: Check NVCC
        shell: bash
        run: |          
          echo "====== $CUDA_PATH ======"
          ls -lah "$CUDA_PATH" || true
          
          echo "====== CUDA_PATH/bin ======"
          ls -la "$CUDA_PATH/bin" || true
          
          echo "====== CUDA_PATH/lib ======"
          ls -la "$CUDA_PATH/lib/x64" || true
          
          echo "====== CUDA_PATH/include ======"
          ls -la "$CUDA_PATH/include" || true
          
